services:
  - type: web
    name: slovar-es-ro-backend
    runtime: node
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run render-start
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MYMEMORY_EMAIL
        sync: false
